name: Publish JSR package
on:
  push:
    branches:
      - master
    # Run this only when the jsr.json file changes  
    paths:
      - 'apps/cli/jsr.json'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Install dependencies
        run: |
          cd ./apps/cli
          pnpm i

      - name: Publish package
        run: |
          cd ./apps/cli
          pnpm dlx jsr publish
